-- AlterTable
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "optionType" TEXT;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "optionAction" TEXT;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "strikePrice" DOUBLE PRECISION;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "spotPrice" DOUBLE PRECISION;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "optionExpiry" TEXT;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "lotSize" INTEGER;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "numberOfLots" INTEGER;
ALTER TABLE "trades" ADD COLUMN IF NOT EXISTS "optionPoints" DOUBLE PRECISION;
